apiVersion: v1
kind: Pod
metadata:
  name: another-pod
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
